version: '3.9'

services:
  web:
    build:
      dockerfile: docker/Dockerfile
      context: .
    ports:
      - "8100:8100"
    command: scripts/web/startup.sh -m -l
    restart: on-failure
    env_file:
      - ./conf/.env
    volumes:
      - .:/code
    depends_on:
      web_db:
        condition: service_healthy
    networks:
      - battleship-network

  web_db:
    image: library/postgres:13.2
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=main_db
    restart: on-failure
    ports:
      - "9432:5432"
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "postgres", "-d", "main_db" ]
      interval: 5s
      retries: 5
    volumes:
      - ./scripts/postgres:/docker-entrypoint-initdb.d
    networks:
      - battleship-network

  redis:
    image: redis:6.2.4
    ports:
      - "9379:6379"
    networks:
      - battleship-network

  prometheus:
   image: prom/prometheus
   command:
     - "--config.file=/etc/prometheus/prometheus_config.yml"
   ports:
     - "9190:9090"
   restart: unless-stopped
   depends_on:
     - web
   volumes:
     - ./prometheus:/etc/prometheus
     - prom_data:/prometheus
   networks:
     - battleship-network

  grafana:
   image: grafana/grafana
   ports:
     - "9000:3000"
   restart: unless-stopped
   volumes:
     - ./grafana:/etc/grafana/provisioning/datasources
   depends_on:
     - web
   networks:
     - battleship-network

volumes:
 prom_data:

networks:
  battleship-network:
    driver: bridge
